# Generated by Django 4.2.7 on 2023-12-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_model_teacher_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/Employee_profile_pic'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/Student_profile_pic'),
        ),
        migrations.AlterField(
            model_name='teacher_model',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/Teacher_profile_pic'),
        ),
    ]
